# Generated by Django 2.2.3 on 2019-08-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_auto_20190801_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.TimeField(),
        ),
    ]
