# Generated by Django 2.2.3 on 2019-08-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0006_remove_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='time',
        ),
    ]
