# Generated by Django 2.2.3 on 2019-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0010_remove_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
