# Generated by Django 2.2.3 on 2019-08-02 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0011_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='time',
        ),
        migrations.AddField(
            model_name='file',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
