# Generated by Django 2.2.3 on 2019-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0012_auto_20190802_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='method',
            field=models.CharField(default='', max_length=20),
        ),
    ]
