# Generated by Django 2.2.3 on 2019-09-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0013_file_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
